name: hubtel_coding_challenge_repo
description: Hibtel coding challenge

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  intl_utils: ^2.8.3
  lottie: ^2.3.2
  provider: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  flutter_staggered_animations: ^1.1.1
  logger: ^1.3.0
  cupertino_icons: ^1.0.5
  flutter_gen: ^5.3.0
  animated_bottom_navigation_bar: ^1.2.0
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.7.0
  injectable: ^2.1.1
  dartz: ^0.10.1
  get_it: ^7.3.0
  envied:
  grpc:
  protoc_plugin: ^20.0.1
  protobuf_google:
  protobuf:
  json_annotation: ^4.8.0
  copy_with_extension:

dependency_overrides:
  logging: 1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  build_runner:
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  envied_generator: ^0.3.0
  json_serializable: ^6.6.0
  copy_with_extension_gen:


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/



flutter_intl:
  enabled: true

# to be able to use svg images with flutter gen
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

